

use forum;
DROP TABLE IF EXISTS Followers;
DROP TABLE IF EXISTS Subscribers;
DROP TABLE IF EXISTS Posts;
DROP TABLE IF EXISTS Threads;
DROP TABLE IF EXISTS Forums;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    email VARCHAR(50) NOT NULL,
    username VARCHAR(50),
    about TEXT,
    name VARCHAR(50),
    isAnonymous BOOLEAN NOT NULL DEFAULT 0,
    UNIQUE KEY(email)
)  ENGINE = INNODB DEFAULT CHARSET=utf8;

CREATE TABLE Forums (
    id INT UNSIGNED AUTO_INCREMENT  NOT NULL PRIMARY KEY,
    name VARCHAR(40) UNIQUE KEY,
    short_name VARCHAR(40) UNIQUE KEY,
    user VARCHAR(50) NOT NULL,
    FOREIGN KEY (user) REFERENCES Users(email)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET=utf8;


CREATE TABLE Threads (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    forum VARCHAR(40),
    user VARCHAR(50) NOT NULL,
    title VARCHAR(50) NOT NULL,
    slug VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    date DATETIME NOT NULL,
    likes INT NOT NULL DEFAULT 0,
    dislikes INT NOT NULL DEFAULT 0,
    isClosed BOOLEAN NOT NULL DEFAULT 0,
    isDeleted BOOLEAN NOT NULL DEFAULT 0,   
    FOREIGN KEY (user) REFERENCES Users(email)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (forum) REFERENCES Forums(short_name)
    ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE = INNODB DEFAULT CHARSET=utf8;

CREATE TABLE  Posts (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    user VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    forum VARCHAR(40),
    thread_id INT UNSIGNED NOT NULL,
    parent INT NULL DEFAULT NULL,
    date DATETIME NOT NULL,
    likes INT NOT NULL DEFAULT 0,
    dislikes INT NOT NULL DEFAULT 0,
    isApproved BOOLEAN NOT NULL DEFAULT 0,
    isHighlighted BOOLEAN NOT NULL DEFAULT 0,
    isEdited BOOLEAN NOT NULL DEFAULT 0,
    isSpam BOOLEAN NOT NULL DEFAULT 0,
    isDeleted BOOLEAN NOT NULL DEFAULT 0,
    Pathlvl1 INT DEFAULT 0,
    Pathlvl2 INT DEFAULT 0,
    Pathlvl3 INT DEFAULT 0,
    Pathlvl4 INT DEFAULT 0,
    INDEX(Pathlvl1,Pathlvl2,id,Pathlvl3,Pathlvl4),
    FOREIGN KEY (user) REFERENCES Users(email)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (thread_id) REFERENCES Threads(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY  (forum) REFERENCES Forums(short_name)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET=utf8;


CREATE TABLE Followers (
    follower VARCHAR(50) NOT NULL,
    followee VARCHAR(50) NOT NULL,
    UNIQUE (followee, follower),
    FOREIGN KEY (follower) REFERENCES Users(email),
    FOREIGN KEY (followee) REFERENCES Users(email)
)ENGINE = INNODB DEFAULT CHARSET=utf8;


CREATE TABLE Subscribers (
    user VARCHAR(50) NOT NULL,
    thread_id INT UNSIGNED  NOT NULL,
    UNIQUE (user, thread_id),
    FOREIGN KEY (user) REFERENCES Users(email)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (thread_id) REFERENCES Threads(id)
) ENGINE = INNODB  DEFAULT CHARSET=utf8;






